blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path(
        "",
        views.index,
        name="index",
    ),
    path(
        "draft-comments/",
        views.draft_comments,
        name="draft_comments",
    ),
    path(
        "<int:post_id>/",
        views.detail,
        name="detail",
    ),
    path(
        "<int:post_id>/comment/create",
        views.create_comment,
        name="create_comment",
    ),
    path(
        "<int:post_id>/comment/draft/create",
        views.create_draft_comment,
        name="create_draft_comment",
    ),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = i18n_patterns(
    path("polls/", include("polls.urls")),
    path("contact/", include("contact.urls")),
    path("blog/", include("blog.urls")),
    path("admin/", admin.site.urls),
    path("subscriptions/", include("subscriptions.urls")),
    path("accounts/", include("accounts.urls")),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _
from .validators import bad_keywords_validator


class Post(models.Model):
    title = models.CharField(_("title"))
    body = models.TextField(_("body"))
    pub_date = models.DateTimeField(_("date published"))

    def __str__(self):
        return str(self.title)


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    name = models.CharField(_("name"))
    email = models.EmailField(_("email"))
    body = models.TextField(_("body"), validators=[bad_keywords_validator])
    created = models.DateTimeField(_("date created"), auto_now_add=True)

    def __str__(self):
        return f"Comment by {self.name} on {self.post}"

blog/forms.py
from .models import Comment
from django import forms


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "email", "body"]

blog/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.contrib import messages

from .forms import CommentForm
from .models import Post
from .sessions import DraftCommentStore


def index(request):
    return render(request, "blog/index.html", {"posts": Post.objects.all()})


def draft_comments(request):
    return render(request, "blog/draft_comments.html")


def detail(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    draft_comment = DraftCommentStore(request).get(post_id)
    return render(
        request,
        "blog/detail.html",
        {
            "post": post,
            "form": CommentForm(
                draft_comment.__dict__ if draft_comment else None
            ),
            "comments": post.comment_set.all(),
        },
    )


def create_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST)
    if not form.is_valid():
        return render(
            request,
            "blog/detail.html",
            {
                "post": post,
                "form": form,
                "comments": post.comment_set.all(),
            },
        )
    comment = form.save(commit=False)
    comment.post = post
    comment.save()

    drafts = DraftCommentStore(request)
    drafts.delete(post_id)

    return HttpResponseRedirect(reverse("blog:detail", args=(post_id,)))


def create_draft_comment(request, post_id):
    drafts = DraftCommentStore(request)
    drafts.add(
        post_id,
        request.POST["name"],
        request.POST["email"],
        request.POST["body"],
    )
    messages.success(request, "Your draft was saved.")
    return HttpResponseRedirect(reverse("blog:detail", args=(post_id,)))

blog/templates/blog/detail.html
{% extends "base.html" %}
{% load i18n %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p>{{ post.body }}</p>
    <section>
        <h2>{% translate "Comments" %}</h2>
        <form action="{% url 'blog:create_comment' post.id %}" method="post">
            {% csrf_token %}
            {{ form }}
            <button>{% translate "Submit" %}</button>
            <button formaction="{% url 'blog:create_draft_comment' post.id %}">
                {% translate "Save draft" %}
            </button>
        </form>
        {% if comments %}
            <ul>
                {% for comment in comments %}
                    <li>
                        <article>
                            <p>{{ comment.body }}</p>
                            <p>{{ comment.author }}</p>
                        </article>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p>{% translate "No comments yet." %}</p>
        {% endif %}
    </section>
{% endblock %}

blog/templates/blog/draft_comments.html
{% if draft_comments %}
    <ul>
        {% for draft in draft_comments %}
            <li>
                <p>{{ draft.body|truncatewords:10 }}</p>
                <p>for {{ draft.post.title }}</p>
                <a href="{% url 'blog:detail' draft.post.id %}">See</a>
            </li>
        {% endfor %}
    </ul>
{% else %}
    <p>No draft comments yet.</p>
{% endif %}

blog/templates/blog/index.html
{% extends "base.html" %}

{% block content %}
    {% if posts %}
        <ul>
            {% for post in posts %}
                <li>
                    <a href="{% url 'blog:detail' post.id %}">
                        {{ post.title }}
                    </a>
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No posts yet.</p>
    {% endif %}
{% endblock %}