accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"
urlpatterns = [
    path(
        "register/",
        views.register,
        name="register",
    ),
    path(
        "register/submit/",
        views.register_submit,
        name="register_submit",
    ),
    path(
        "login/",
        views.login,
        name="login",
    ),
    path(
        "login/submit/",
        views.login_submit,
        name="login_submit",
    ),
    path(
        "logout",
        views.logout,
        name="logout",
    ),
    path(
        "detail/",
        views.detail,
        name="detail",
    ),
]

blog/urls.py
from django.urls import path
from . import views

app_name = "blog"
urlpatterns = [
    path(
        "",
        views.index,
        name="index",
    ),
    path(
        "draft-comments/",
        views.draft_comments,
        name="draft_comments",
    ),
    path(
        "<int:post_id>/",
        views.detail,
        name="detail",
    ),
    path(
        "<int:post_id>/comment/create",
        views.create_comment,
        name="create_comment",
    ),
    path(
        "<int:post_id>/comment/draft/create",
        views.create_draft_comment,
        name="create_draft_comment",
    ),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns


urlpatterns = i18n_patterns(
    path("polls/", include("polls.urls")),
    path("contact/", include("contact.urls")),
    path("blog/", include("blog.urls")),
    path("admin/", admin.site.urls),
    path("subscriptions/", include("subscriptions.urls")),
    path("accounts/", include("accounts.urls")),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/templates/partials/header.html
{% load i18n %}

<header>
    <a href="{% url 'blog:draft_comments' %}">
        {% blocktranslate with count=draft_comments|length %}
        Draft comments: {{ count }}
        {% endblocktranslate %}
    </a>
    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
                <li {% if message.tags %}class="{{ message.tags }}"{% endif %}>
                    {{ message }}
                </li>
            {% endfor %}
        </ul>
    {% endif %}
    {% if user.is_authenticated %}
        <a href="{% url 'accounts:logout' %}">{% translate 'Logout' %}</a>
    {% endif %}
</header>